### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by hr2894235132** [Taeyoung96/GTSAM-example-supplementary#1]
Hi！Thank you for sharing！Do you have an English version? I can't check the translation in pdf, it's too difficult for me to read。

**Comment by Taeyoung96** [comment]
@hr2894235132   
Thanks for your interest!  
These materials are just for personal studying, so I don't have any plans to translate my pdf. :smiling_face_with_tear:   
However, you could use these materials in Google slide on [this link](https://docs.google.com/presentation/d/13AFg8z7nwNj6dJr_KP_cU6Y1E1S4upXgbM3D4yqkrNY/edit?usp=sharing).  
I gave the editing authority to the link, so I think it will be possible to edit it in English.  :+1:

**Comment by hr2894235132** [comment]
> @hr2894235132 Thanks for your interest! These materials are just for personal studying, so I don't have any plans to translate my pdf. smiling_face_with_tear However, you could use these materials in Google slide on [this link](https://docs.google.com/presentation/d/13AFg8z7nwNj6dJr_KP_cU6Y1E1S4upXgbM3D4yqkrNY/edit?usp=sharing). I gave the editing authority to the link, so I think it will be possible to edit it in English. +1

Thank you very much for your reply！This makes translation much easier.I wish you good work and good health!
